export * from './IAecoRepository'
export * from './ICompanyRepository'
export * from './IPageRepository'
export * from './IRewardRepository'
export * from './IUserRepository'
export * from './ISettingRepository'
export * from './IRoleRepository'
